# emp.service.url=http://localhost:678/getEmpList

my:
  greeting: Hello From Github Server
  list:
    value: One,Tow,Three,Four

app:
  name: My app From Github Config Server
  description: Welcome to ${app.name}
